# Generated by Django 3.1.6 on 2021-02-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='question_name',
            new_name='name',
        ),
    ]
