# Generated by Django 3.1.6 on 2021-02-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankdimensions',
            name='depth',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tankdimensions',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tankdimensions',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
