# Generated by Django 3.1.6 on 2021-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0002_auto_20210204_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='fauna',
            field=models.ManyToManyField(null=True, to='aquarium.Fauna'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='flora',
            field=models.ManyToManyField(null=True, to='aquarium.Flora'),
        ),
    ]
